apiVersion: skaffold/v1beta2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/cong-xiu/jenkins-x-kubernetes:{{.VERSION}}"
  artifacts:
  - image: changeme
    context: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/cong-xiu/jenkins-x-kubernetes:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: jenkins-x-kubernetes
        chartPath: charts/jenkins-x-kubernetes
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/cong-xiu/jenkins-x-kubernetes"
          image.tag: "{{.DIGEST_HEX}}"
